<?php
/**
 * @file
 * Ylikäyttäjän oikeuksien lisäys sivu
 *
 * TAMKin oppimisympäristö, Pupesoft
 * ylikayttaja_oikeudet.php
 * Author: Ari Marin, Janne Vihikangas
 * Created: 22.08.2013
 * Modified:
 *
 */
 
	// Lisätty 16.8.2013, LOCK TABLES ja hirmuinen insert hirviö, jolla saadaan yrityksen luonnin yhteydessä superuserille kaikki mahdolliset oikeudet (luultavasti turhiakin...)
	$query = "LOCK TABLES oikeu WRITE";
	$result = mysql_query($query) or pupe_error($query);

	$query = "INSERT into oikeu (kuka, sovellus, nimi, alanimi, paivitys, lukittu, nimitys, jarjestys, jarjestys2, profiili, yhtio, hidden) VALUES ('superuser', '', '', '', '1', '', '', 0, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'kopioiasiakas.php', '', '1', '', 'Kopioi asiakas', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'kopioiasiakasalennus.php', '', '1', '', 'Kopioi asiakasale', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakas', '1', '', 'Asiakasylläpito', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakas!!!PROSPEKTI!!!PROSPEKTI&laji=R', '1', '', 'Prospektit', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakas!!!TUKKUMYYNTI!!!true&laji=Y', '1', '', 'Yritysasiakkaat', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakas!!!VAHITTAISMYYNTI!!!true&laji=H', '1', '', 'Yksityisasiakkaat', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakas&laji=P', '1', '', 'Poistetut asiakkaat', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakasalennus', '1', '', 'Asiakasalennukset', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakashinta', '1', '', 'Asiakashinnat', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakaskommentti', '1', '', 'Asiakaskommentit', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakkaan_avainsanat', '1', '', 'Asiakkaan avainsanat', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakkaan_kohde', '1', '', 'Kohteet', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'asiakkaan_positio', '1', '', 'Positiot', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'hinnasto', '1', '', 'Hinnastot', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'perusalennus', '1', '', 'Alennusryhmät', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Asiakkaat', 'yllapito.php', 'yhteyshenkilo', '1', '', 'Yhteyshenkilöt', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/asiakaslista.php', '', '1', '', 'Asiakaslista', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/asiakasmemo.php', '', '1', '', 'Asiakasmemo', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/kalenteri.php', '', '1', '', 'Kalenteri', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/kuittaamattomat.php', '', '1', '', 'Muistutukset', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/kuukausinakyma.php', '', '1', '', 'Kuukausinäkymä', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/lomaseuranta.php', '', '1', '', 'Lomaseuranta', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/tarrat.php', '', '1', '', 'Tulosta osoitetarrat', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/todo.php', '', '1', '', 'Todo-lista', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/viikkosuunnitelma.php', '', '1', '', 'Viikkosuunnitelma', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'crm/viikkosuunnitelma_raportti.php', '', '1', '', 'Edustajaraportti', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'extranet/asiakashinnasto.php', '', '1', '', 'Asiakashinnasto', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'lahetamuistutus.php', '', '1', '', 'Lähetä muistutukset', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'projektikalenteri.php', '', '1', '', 'Projektikalenteri', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'raportit/abc_asiakas.php', 'kate', '1', '', 'ABC Asiakas kate', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'raportit/abc_asiakas.php', 'kpl', '1', '', 'ABC Asiakas kpl', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'raportit/abc_asiakas.php', 'myynti', '1', '', 'ABC Asiakas myynti', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'raportit/abc_asiakas.php', 'rivia', '1', '', 'ABC Asiakas rivit', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'raportit/asiakasinfo.php', '', '1', '', 'Asiakkaan perustiedot', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'CRM', 'tekstiviesti.php', '', '1', '', 'Tekstiviestit', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ennakkomyynti', 'muokkaatilaus.php', 'ennakko', '1', '', 'Ennakkotilaukset', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ennakkomyynti', 'tilauskasittely/jtselaus.php', 'ENNAKKO', '1', '', 'Ennakko-selaus', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ennakkomyynti', 'tilauskasittely/tilaus_myynti.php', 'ENNAKKO', '1', '', 'Uusi Ennakkotilaus', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ennakkomyynti', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ennakkomyynti', 'tuote.php', '', '1', '', 'Tuotekysely', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'asiakashinnasto.php', '', '1', '', 'Asiakashinnasto', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'asiakasinfo.php', '', '1', '', 'Alennustaulukot', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'asiakkaantilaukset.php', '', '1', '', 'Tilaushistoria', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'extranethinnastoajotab.php', '', '1', '', 'Hinnastoajo', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'hinnasto.php', '', '1', '', 'Hinnastoajot', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'hinnastofile2.php', '', '1', '', 'Hinnastoajo', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'jtrivit_tilaukselle.php', '', '1', '', 'Jälkitoimitusseuranta', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'jtselaus.php', '', '1', '', 'Jälkitoimitusseuranta', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'osasto_tuotemerkeittain.php', '', '1', '', 'Ostojen seuranta', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'tervetuloa.php', '', '1', '', 'Etusivu', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'tilaus_myynti.php', 'EXTRANET', '1', '', 'Tilauksesi', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'tulostakopio.php', 'LAHETE', '1', '', 'Lähetekopio', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'tulostakopio.php', 'LASKU', '1', '', 'Laskukopio', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet', 'vertailut.php', '', '1', '', 'Vertailut', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Extranet-Verkkokauppa', 'verkkokauppa.php', '', '1', '', 'Verkkokauppa', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'crm/hyvaksynnat.php', '', '1', '', 'Lomahyväksyntä', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'crm/kalenteri.php', '', '1', '', 'Kalenteri', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'crm/kuukausinakyma.php', '', '1', '', 'Kuukausinäkymä', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'messenger.php', '', '1', '', 'Messenger', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'ruokalista.php', '', '1', '', 'Ruokalistat', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'tervetuloa.php', '', '1', '', 'Etusivu', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'uutiset.php', '', '1', '', 'Uutiset', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'uutiset.php', 'ASIAKASPALVELU', '1', '', 'Asiakaspalvelu', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'uutiset.php', 'EXTRANET', '1', '', 'Extranet-Uutiset', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'uutiset.php', 'VERKKOKAUPPA', '1', '', 'Verkkokauppasivut', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'uutiset.php', 'VIIKKOPALAVERI', '1', '', 'Viikkopalaveri', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'varauskalenteri/varauskalenteri.php', 'Sauna', '1', '', 'Varausk. Sauna', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'varauskalenteri/varauskalenteri.php', 'Tapahtumat', '1', '', 'Tapahtumakalenteri', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'yhteystiedot.php', '', '1', '', 'Yhteystiedot', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Intranet', 'yrityspeli/tyoajanseuranta.php', '', '1', '', 'Työtuntien kirjaus', 15, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'kayttajaprofiilit.php', '', '1', '', 'Käyttäjäprofiilit', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'kayttajat.php', '', '1', '', 'Käyttäjähallinta', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'kayttajat.php', 'extranet', '1', '', 'Extranet-k', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'kopioi_oikeuksia.php', '', '1', '', 'Kopioi käyttöoikeuksia', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'kopioi_profiili.php', '', '1', '', 'Kopioi profiili', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'menut.php', '', '1', '', 'Valikot', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'suoja.php', '', '1', '', 'Käyttöoikeudet', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'suoja.php', 'extranet', '1', '', 'Extranet-käyttäjähallinta', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Käyttäjät ja valikot', 'suoja.php', 'extranet', '1', '', 'Extranet-käyttöoikeudet', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'budjetinyllapito.php', '', '1', '', 'Budjettimatriisi', 100, 50, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'hae_valuutat.php', '', '1', '', 'Päivitä kurssit', 100, 80, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'konsernitosite.php', '', '1', '', 'Uusi konsernitosite', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'kopioitilikartta.php', '', '1', '', 'Kopioi tilikartta', 100, 130, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'maksu.php', '', '1', '', 'Muut maksut', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'muutosite.php', '', '1', '', 'Tiliöinnin muutos', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'palkkatosite.php', '', '1', '', 'Palkkatosite', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'raportit.php', 'eliminoi', '1', '', 'Eliminoi', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'raportit.php', 'laskuhaku', '1', '', 'Laskuhaku', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'raportit.php', 'toimittajahaku', '1', '', 'Toimittajahaku', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'raportit/tuloslaskelma.php', 'TASOMUUTOS', '1', '', 'Tase/tuloslaskelma tasomuutos', 100, 30, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'suori.php', '', '1', '', 'Suoritukset', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'tiliointisaannot.php', '', '1', '', 'Tiliöintisäännöt', 100, 100, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'tiliote.php', '', '1', '', 'Tiliotteen käsittely', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'tiliotesaannot.php', '', '1', '', 'Tiliotesäännöt', 100, 110, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'tosite.php', '', '1', '', 'Uusi muu tosite', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', '', '1', '', 'Ylläpito', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'budjetti', '1', '', 'Budjetin ylläpito', 100, 60, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'kustannuspaikka', '1', '', 'Tarkenteet', 100, 40, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'taso', '1', '', 'Tilikartan rakenne', 100, 20, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'tili', '1', '', 'Tilikartta', 100, 10, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'tilikaudet', '1', '', 'Yrityksen tilikaudet', 100, 120, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'valuu', '1', '', 'Valuutat', 100, 70, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'yhtio', '1', '', 'Yritystiedot', 100, 140, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'yhtion_toimipaikat', '1', '', 'Yhtiön toimipaikat', 15, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpito', 'yllapito.php', 'yriti', '1', '', 'Yrityksen pankkitilit', 100, 90, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'alv', '1', '', 'ALV-raportti', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'avoimet', '1', '', 'Avoimet laskut', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'eliminoi', '1', '', 'Eliminoi', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'hyvaksynta', '1', '', 'Hyväksynnän tila', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'konsernitasmaytys', '1', '', 'Konsernitäsmäytys', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'laskutila', '1', '', 'Laskut tilansa mukaan', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'maksuvalmius', '1', '', 'Maksuvalmius', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'ostovelat', '1', '', 'Sidottupääoma', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'paakirja', '1', '', 'Pää- ja päiväkirja', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'tilisaldot', '1', '', 'Tiliensaldot', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit.php', 'tilitkk', '1', '', 'Tilit kuukausittain', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/alv_laskelma.php', '', '1', '', 'ALV-laskelma -2009', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/alv_laskelma_uusi.php', '', '1', '', 'ALV-laskelma 2010-', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/matkallaolevat_laskuittain.php', '', '1', '', 'Matkallaolevat laskuittain', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/tarkista_tilit.php', '', '1', '', 'Tarkista tilit', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/tilioinnit_lajeittain.php', '', '1', '', 'Tiliöinnit lajeittain', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/tuloslaskelma.php', '', '1', '', 'Tase/tuloslaskelma', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'raportit/verottomat_korvaukset.php', '', '1', '', 'Verottomat-korvaukset', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'selaajamuuta.php', '', '1', '', 'Tiliöinnin tarkastus', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'tilioteselailu.php', '', '1', '', 'Näytä tiliote', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'tiliotetarkistukset.php', '', '1', '', 'Tiliotetarkistukset', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Kirjanpitoraportit', 'viranomaisilmoitukset.php', '', '1', '', 'TYVI-ilmoitus', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Mobiili', 'keikka.php', '', '1', '', 'Keikka', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Mobiili', 'keikkaselaus.php', '', '1', '', 'Keikkaselaus', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Mobiili', 'tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Mobiili', 'tuvar.php', '', '1', '', 'Tuotehaku', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'db_sql_query.php', '', '1', '', 'SQL hakugeneraattori', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'peruutatikon.php', '', '1', '', 'TIKON Peruuta', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/atk-tilintarkastus.php', '', '1', '', 'Atk-tilintarkastus', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/autolink_hinnasto.php', '', '1', '', 'Hinnastoajo', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/avoimet_viennit.php', '', '1', '', 'Avoimet vientitilaukset', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/hinnastoraportti.php', '', '1', '', 'Hinnastoraportti', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/kehahinseuranta.php', '', '1', '', 'Kehahinan seuranta', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/konsernimyynnit.php', '', '1', '', 'Konsernimyynnit', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/laskutuksentilioinnit.php', '', '1', '', 'Laskutuksen tiliöinnit', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/merivakuutukset.php', '', '1', '', 'Merivaakuutuslistaus', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/sarjanumeroiden_saldot.php', '', '1', '', 'Korjaa sarjanumeroiden saldot', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/sarjanumerotarkistukset.php', '', '1', '', 'Tarkista laitemyynnit', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/sarjanumerovssaldo.php', '', '1', '', 'Sarjanumerot/Saldot', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/sql-query.php', '', '1', '', 'SQL haku', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/tavarakatelista.php', '', '1', '', 'Tavarakatelistaus', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/tyom_tuntiraportti.php', '', '1', '', 'Tuntiraportti', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'raportit/vuosisopimusasiakkaat.php', '', '1', '', 'Vuosisopimusasiakkaat', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'tarkistareskontrat.php', '', '1', '', 'Reskontra tarkistus', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'tikon.php', '', '1', '', 'TIKON file', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Muut raportit', 'tilauskasittely/elmatuote.php', '', '1', '', 'Elmatuote', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'maksusopimus_laskutukseen.php', '', '1', '', 'Maksusopimukset', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'monistalasku.php', '', '1', '', 'Monista lasku', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'monistalasku.php', 'TILAUS', '1', '', 'Monista tilaus', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'muokkaatilaus.php', '', '1', '', 'Avoimet tilaukset', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'muokkaatilaus.php', 'EXTRANET', '1', '', 'Hyväksyttävät EXT-tilaukset', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'muokkaatilaus.php', 'JTTOIMITA', '1', '', 'JT-tilaukset', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'muokkaatilaus.php', 'LASKUTUSKIELTO', '1', '', 'Laskutuskiellossa', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'muokkaatilaus.php', 'super', '1', '', 'Muokkaa tilausta', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'raportit/asiakkaantilaukset.php', 'MYYNTI', '1', '', 'Asiakkaan tilaukset', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/jtselaus.php', '', '1', '', 'JT-selaus', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/sarjanumeroseuranta.php', '', '1', '', 'Sarjanumeroseuranta', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tilaus_in.php', '', '1', '', 'Tilausten sisäänluku', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tilaus_myynti.php', 'PIKATILAUS', '1', '', 'Uusi Pikatilaus', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tilaus_myynti.php', 'RIVISYOTTO', '1', '', 'Uusi Tilaus', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tulostakopio.php', 'LAHETE', '1', '', 'Lähete kopio', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tulostakopio.php', 'LASKU', '1', '', 'Lasku kopio', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tulostakopio.php', 'TILAUSVAHVISTUS', '1', '', 'Tilausvahvistus kopio', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', '', '1', '', 'Laskuta tilaus', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', 'VAINLASKUTA', '1', '', 'Laskuta tilaus', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tuote.php', '', '1', '', 'Tuotekysely', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myynti', 'tuvar.php', '', '1', '', 'Tuotekysely (Shop)', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_asiakas.php', 'kate', '1', '', 'ABC Asiakas kate', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_asiakas.php', 'kpl', '1', '', 'ABC Asiakas kpl', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_asiakas.php', 'myynti', '1', '', 'ABC Asiakas myynti', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_asiakas.php', 'rivia', '1', '', 'ABC Asiakas rivit', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_tuote.php', 'kate', '1', '', 'ABC Tuote kate', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_tuote.php', 'kpl', '1', '', 'ABC Tuote kpl', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_tuote.php', 'kulutus', '1', '', 'ABC Tuote kulutus', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_tuote.php', 'myynti', '1', '', 'ABC Tuote myynti', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/abc_tuote.php', 'rivia', '1', '', 'ABC Tuote rivit', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/asiakas_piiri_myynnit.php', '', '1', '', 'Asiakas piirimyynnit', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/asiakkaan_kokonaismyynnit.php', '', '1', '', 'Asiakas/kokonaismyynti', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/asiakkaan_ostot_kausi.php', '', '1', '', 'Asiakkaan ostot kaudelta', 270, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/asiakkaan_tilaukset_tuotteittain.php', 'MYYNTI', '1', '', 'Asiakkaan tuoteostot', 260, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/asiakkostotoim.php', '', '1', '', 'As.ostot toimittajittain', 330, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/hyvityslaskujen_seuranta.php', '', '1', '', 'Hyvitys seuranta', 350, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/kateismyynnit.php', '', '1', '', 'Käteismyynnit', 250, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/kehahinseuranta.php', '', '1', '', 'Kehahintaseuranta', 320, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/menossa_olevat.php', '', '1', '', 'Menossa olevat', 360, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/myohassa_olevat.php', '', '1', '', 'Myöhässä olevat', 370, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/myymyyjat.php', '', '1', '', 'Myyjien myynnit', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/myyntiasiakkaittain.php', '', '1', '', 'Myynti asiakkaittain', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/myyntiseuranta.php', '', '1', '', 'Myynninseuranta', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/myytuory.php', '', '1', '', 'Myynnit tuoterymittäin', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/myytuory_kausi.php', '', '1', '', 'Mytuory kausi', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/osasto_tuotemerkeittain.php', '', '1', '', 'Osastot merkeittäin', 300, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/paivamyynnit.php', '', '1', '', 'Myynti päivittäin', 290, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/piiaomo.php', '', '1', '', 'Piirimyynnit', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/puutteet.php', '', '1', '', 'Puutelistaus', 310, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/rivilaskuri.php', '', '1', '', 'Rivilaskuri', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/tilauksien_seuranta.php', '', '1', '', 'Toteutuneet tilaukset', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/tilaushakukone.php', 'TILAUSHAKUKONE', '1', '', 'Tilaushakukone', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/tilauskanta_laskutus.php', '', '1', '', 'Tilauskanta, Tilaukset, Laskut', 340, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/tuorymyynnit-screen.php', '', '1', '', 'Tuoteryhmien myynnit', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/tuorymyynnit.php', '', '1', '', 'Asiakas/tuoteryhmä', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'raportit/vertailu.php', '', '1', '', 'Vertaa myyntejä', 280, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'tilauskasittely/selaa_tilauksia.php', 'MYYNTI', '1', '', 'Myyntiselaus', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntiraportit', 'tilauskasittely/tilauskanta.php', '', '1', '', 'Tilauskanta', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/eikateinen.php', '', '1', '', 'Ei käteinen', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/factoring.php', '', '1', '', 'Muuta factoringlaskuksi', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/factoringkorko.php', '', '1', '', 'Factoringkorot', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/karhu.php', '', '1', '', 'Karhu', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/karhuselaa.php', '', '1', '', 'Karhujen selaus', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/karhuselaa.php', 'TRATTA', '1', '', 'Trattaselaus', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/korkolasku.php', '', '1', '', 'Korkolaskut', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/luottotappiot.php', '', '1', '', 'Luottotappiot', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/maksunsyotto.php', '', '1', '', 'Suorituksen käsinsyöttö', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/manuaalinen_suoritusten_kohdistus.php', '', '1', '', 'Manuaalikohdistus', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/myyntilaskuhaku.php', '', '1', '', 'Laskuhaku', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/myyntilaskujen_selaus.php', '', '1', '', 'Myyntilaskujenselaus', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/myyntilaskut_asiakasraportti.php', '', '1', '', 'Asiakasraportit', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/paittainmenevat.php', '', '1', '', 'Päittän menevät suoritukset', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/paittainmenevat.php', 'SUPER', '1', '', 'Päittän menevät suoritukset', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/suoritusselailu.php', '', '1', '', 'Suoritukset', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'myyntires/tratta.php', '', '1', '', 'Tratta', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'raportit.php', 'avoimet', '1', '', 'Avoimet laskut', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'raportit/factoringstemmuutus.php', '', '1', '', 'Factoringtäsmäytys', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'raportit/kateismyynnit.php', '', '1', '', 'Käteismyynnit', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'raportit/saatanat.php', '', '1', '', 'Saatavat', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntireskontra', 'tilauskasittely/tulostakopio.php', 'LASKU', '1', '', 'Laskukopio', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'muokkaatilaus.php', 'MYYNTITILI', '1', '', 'Myyntitilit', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'muokkaatilaus.php', 'MYYNTITILISUPER', '1', '', 'Muokkaa myyntitiliä', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'muokkaatilaus.php', 'MYYNTITILITOIMITA', '1', '', 'Laskuta myyntitili', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'tilauskasittely/keraa.php', 'MYYNTITILI', '1', '', 'Kerää myyntitili', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'tilauskasittely/lahetteen_tulostusjono.php', 'MYYNTITILI', '1', '', 'Tulosta myyntitili', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'tilauskasittely/tilaus_myynti.php', 'MYYNTITILI', '1', '', 'Uusi myyntitili', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'tilauskasittely/tulostakopio.php', 'SIIRTOLISTA', '1', '', 'Myyntitili kopio', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'tilauskasittely/vastaanota.php', 'MYYNTITILI', '1', '', 'Toimita myyntitili', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Myyntitilit', 'tuote.php', '', '1', '', 'Tuotekysely', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'opettajaraportit.php', 'Opettajaraportit', '1', '', 'Valitse yritys', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit.php', 'paakirja', '1', '', 'Pää / päiväkirja', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/myyntiseuranta.php', '', '1', '', 'Myynnin seuranta', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/ostotilausten_seuranta.php', '', '1', '', 'Ostotilausten seuranta', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/saatanat.php', '', '1', '', 'Saatavat', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/tilanneraportti.php', '', '1', '', 'Tilanneraportti', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/tilauskanta_laskutus.php', '', '1', '', 'Tilauskanta', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/tuloslaskelma.php', '', '1', '', 'Tuloslaskelma', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/tyotuntiraportti.php', '', '1', '', 'Työtuntiraportti', 45, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'raportit/varastotilasto.php', '', '1', '', 'Varastotilasto', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Opettajat', 'tilanneraportti.php', '', '1', '', 'Tilanne', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'kopioitoimittaja.php', '', '1', '', 'Kopioi toimittaja', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'muokkaatilaus.php', 'HAAMU', '1', '', 'Avoimet tarvikeostot', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'muokkaatilaus.php', 'OSTO', '1', '', 'Avoimet tilaukset', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'muokkaatilaus.php', 'OSTOSUPER', '1', '', 'Muokkaa tilausta', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'raportit/asiakkaantilaukset.php', 'OSTO', '1', '', 'Toimittajan tilaukset', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'teeytunnus.php', '', '1', '', 'Luo ytunnus', 105, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/keikka.php', '', '1', '', 'Saapuva keikka', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/ostolaskunvarastopaikat.php', '', '1', '', 'Keikan varastopaikat', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/ostotilausrivien_hallinta.php', '', '1', '', 'Avoimet ostorivit', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tilaus_osto.php', '', '1', '', 'Uusi ostotilaus', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tilaus_osto.php', 'HAAMU', '1', '', 'Työ/tarvikeosto', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tulostakopio.php', 'HAAMU', '1', '', 'Työ/tarvikeostokopio', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tulostakopio.php', 'OSTO', '1', '', 'Ostotilauskopio', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tulostakopio.php', 'PURKU', '1', '', 'Purkulistakopio', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tulostakopio.php', 'TARIFFI', '1', '', 'Tariffilistakopio', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tulostakopio.php', 'TUOTETARRA', '1', '', 'Tuotetarrakopio', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja Selaa', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'tuote.php', '', '1', '', 'Tuotekysely', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Osto', 'yllapito.php', 'toimi', '1', '', 'Toimittajat', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/asiakkaan_tilaukset_tuotteittain.php', 'OSTO', '1', '', 'Toimittajalta tilatut', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/halytysraportti.php', '', '1', '', 'Hälytysraportti', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/ostoehdotus.php', '', '1', '', 'Ostoehdotus', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/ostoehdotus_cs.php', '', '1', '', 'Ostoehdotus CS', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/ostoraportti.php', '', '1', '', 'Ostoraportti', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/ostoseuranta.php', '', '1', '', 'Ostoseuranta', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/ostotilausten_seuranta.php', '', '1', '', 'Ostotilausten seuranta', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/tulossa_olevat.php', '', '1', '', 'Tulossa olevat', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'raportit/varastoonrivit.php', '', '1', '', 'Varastoonviedyt', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'tilauskasittely/selaa_tilauksia.php', 'KEIKKA', '1', '', 'Keikkaselaus', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'tilauskasittely/selaa_tilauksia.php', 'OSTO', '1', '', 'Ostoselaus', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoraportit', 'tilauskasittely/tilauskanta2.php', '', '1', '', 'Saldovajeet', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'hyvak.php', '', '1', '', 'Laskujen hyväksyntä', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'hyvak.php', '', '1', '', 'Laskujen hyväksyntä', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'makai.php', '', '1', '', 'Tee maksuaineistot', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'maksa.php', '', '1', '', 'Maksa laskuja', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'matkalasku.php', '', '1', '', 'Matkalasku', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'matkalasku.php', '', '1', '', 'Matkalasku', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'matkalasku.php', 'SUPER', '1', '', 'Matkalasku (S)', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'matkalasku.php', 'SUPER', '1', '', 'Matkalasku (S)', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'muutosite.php', '', '1', '', 'Tiliöinnin muutos', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'muutosite.php', '', '1', '', 'Tiliöinnin muutos', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'nouda_maksuaineisto.php', '', '1', '', 'Selaa maksuaineistoja', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'nouda_maksuaineisto.php', '', '1', '', 'Selaa maksuaineistoja', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'avoimet', '1', '', 'Avoimet laskut', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'avoimet', '1', '', 'Avoimet laskut', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'hyvaksynta', '1', '', 'Hyväksynnän tila', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'hyvaksynta', '1', '', 'Hyväksynnän tila', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'keikanlaskut', '1', '', 'Varaston laskut', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'keikanlaskut', '1', '', 'Varaston laskut', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskuerapvm', '1', '', 'Laskut per eräpvm', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskuerapvm', '1', '', 'Laskut per eräpvm', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskuhaku', '1', '', 'Laskuhaku', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskutila', '1', '', 'Laskut tilansa mukaan', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskutila', '1', '', 'Laskut tilansa mukaan', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskuvaluutta', '1', '', 'Laskut per valuutta', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'laskuvaluutta', '1', '', 'Laskut per valuutta', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'maksuvalmius', '1', '', 'Maksuvalmius', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'maksuvalmius', '1', '', 'Maksuvalmius', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit.php', 'toimittajahaku', '1', '', 'Toimittajahaku', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit/maksuvalmius.php', '', '1', '', 'Maksuvalmius 2', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'raportit/maksuvalmius.php', '', '1', '', 'Maksuvalmius 2', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'selaa_maksuaineisto.php', '', '1', '', 'Etsi maksuaineistoja', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'sepa.php', '', '1', '', 'Tee SEPA maksuaineisto', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'suoraveloitussuoritus.php', '', '1', '', 'Suoraveloitus suoritus', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'suoraveloitussuoritus.php', '', '1', '', 'Suoraveloitus suoritus', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'suori.php', '', '1', '', 'Suoritukset', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'suori.php', '', '1', '', 'Suoritukset', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'ulask.php', '', '1', '', 'Uusi lasku', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'virtuaalipankkiaineisto.php', '', '1', '', 'Aineistopankkiin', 51, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'virtuaalipankkiaineisto.php', 'aineistopankki', '1', '', 'Aineisto pankkiin', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'liitetiedostot', '1', '', 'Liitetiedostot', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'liitetiedostot', '1', '', 'Liitetiedostot', 270, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'toimi', '1', '', 'Toimittajat', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'toimi', '1', '', 'Toimittajat', 250, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'toimi!!!KAYTTAJA!!!true', '1', '', 'Käyttäjätiedot', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'toimi!!!KAYTTAJA!!!true', '1', '', 'Käyttäjätiedot', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'yriti', '1', '', 'Yrityksen pankkitilit', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ostoreskontra', 'yllapito.php', 'yriti', '1', '', 'Yrityksen pankkitilit', 260, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'annalainaa.php', '', '1', '', 'Anna lainaa', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'pankkisiirto.php', '', '1', '', 'Uusi maksu', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'pankkitiliote.php', '', '1', '', 'Pankkitiliote', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'tito.php', '', '1', '', 'Tiliotetiedosto', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'yllapito.php', 'pankkitapahtuma', '1', '', 'Pankin tapahtumat', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'yllapito.php', 'pankkitili', '1', '', 'Pankkitilit', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Pankki', 'yrityspeli/lainat.php', '', '1', '', 'Lainat', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Projektit', 'liita_projektiin.php', '', '1', '', 'Liitä tilaus projektiin', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Projektit', 'muokkaatilaus.php', 'PROJEKTI', '1', '', 'Avoimet projektit', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Projektit', 'tilauskasittely/tilaus_myynti.php', 'PROJEKTI', '1', '', 'Uusi Projekti', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Reklamaatiot', 'muokkaatilaus.php', 'REKLAMAATIO', '1', '', 'Muokkaa reklamaatioita', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Reklamaatiot', 'raportit/asiakkaantilaukset.php', 'REKLAMAATIO', '1', '', 'Asiakkaan reklamaatiot', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Reklamaatiot', 'tilauskasittely/tilaus_myynti.php', 'REKLAMAATIO', '1', '', 'Uusi reklamaatio', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Reklamaatiot', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Reklamaatiot', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', '', '1', '', 'Laskuta tilaus', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Reklamaatiot', 'tuote.php', '', '1', '', 'Tuotekysely', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sisäinen työmääräys', 'muokkaatilaus.php', 'SIIRTOTYOMAARAYS', '1', '', 'Sisäiset työmääräykset', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sisäinen työmääräys', 'tilauskasittely/keraa.php', 'SIIRTOTYOMAARAYS', '1', '', 'Kerää sis. työmäääräys', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sisäinen työmääräys', 'tilauskasittely/lahetteen_tulostusjono.php', 'SIIRTOTYOMAARAYS', '1', '', 'Tulosta sis. työmääräys', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sisäinen työmääräys', 'tilauskasittely/sistyomaarays_irrota.php', '', '1', '', 'Irrota lisävaruste', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sisäinen työmääräys', 'tilauskasittely/sistyomaarays_valmis.php', '', '1', '', 'Sis. työmääräys valmis', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sisäinen työmääräys', 'tilauskasittely/tilaus_myynti.php', 'SIIRTOTYOMAARAYS', '1', '', 'Uusi sis. työmääräys', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sopimukset', 'muokkaatilaus.php', 'YLLAPITO', '1', '', 'Muokkaa sopimuksia', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sopimukset', 'tilauskasittely/tilaus_myynti.php', 'YLLAPITO', '1', '', 'Uusi sopimus', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Sopimukset', 'tilauskasittely/yllapitosopimukset.php', '', '1', '', 'Laskuta sopimuksia', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'crm/kuittaamattomat.php', '', '1', '', 'Muistutukset', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'monistalasku.php', 'TARJOUS', '1', '', 'Monista tarjous', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'muokkaatilaus.php', 'TARJOUS', '1', '', 'Avoimet tarjoukset', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'muokkaatilaus.php', 'TARJOUSSUPER', '1', '', 'Muokkaa Tarjouksia', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'raportit/asiakkaantilaukset.php', 'TARJOUS', '1', '', 'Asiakkaan tarjoukset', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'tilauskasittely/sarjanumeroseuranta.php', '', '1', '', 'Sarjanumeroseuranta', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'tilauskasittely/tilaus_myynti.php', 'TARJOUS', '1', '', 'Uusi Tarjous', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'tilauskasittely/tulostakopio.php', 'TARJOUS', '1', '', 'Tarjouskopio', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjous', 'tuote.php', '', '1', '', 'Tuotekysely', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjousraportit', 'raportit/tilauksien_seuranta.php', 'TARJOUS', '1', '', 'Tehdyt tarjoukset', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjousraportit', 'raportit/tilaushakukone.php', 'TARJOUSHAKUKONE', '1', '', 'Tarjousseuranta', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tarjousraportit', 'raportit/tilaushakukone.php', 'TARJOUSHAKUKONE&setti=omat', '1', '', 'Tarjoukseni', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'datan_massalisays.php', '', '1', '', 'Tuo/Vie tuotekuvia', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'epakurantti.php', '', '1', '', 'Epäkurantit', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'hinnasto.php', '', '1', '', 'Hinnastoajot', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'kopioituote.php', '', '1', '', 'Kopioi tuote', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'korvaavat.php', '', '1', '', 'Korvaavat', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'lue_data.php', '', '1', '', 'Sisäänlue dataa', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'lue_tpaikka_haly.php', '', '1', '', 'Lue hälyrajoja', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'lue_tuoteketjuja.php', '', '1', '', 'Lue tuoteketjuja', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tullinimikkeet.php', '', '1', '', 'Tullinimikkeet', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tulosta_tuotetarrat.php', '', '1', '', 'Tulosta tuotetarrat EAN', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tulosta_tuotetarrat.php', 'YKS', '1', '', 'Tulosta tuotetarrat YKS', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tuote.php', '', '1', '', 'Tuotekysely', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tuoteperhe.php', 'LISAVARUSTE', '1', '', 'Lisävarusteet', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tuoteperhe.php', 'PERHE', '1', '', 'Tuoteperheet', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'tuoteperhe.php', 'RESEPTI', '1', '', 'Tuotereseptit', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'vaihda_tuoteno.php', '', '1', '', 'Vaihda tuotenumeroita', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'hinnasto', '1', '', 'Tuotehinnasto', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'liitetiedostot', '1', '', 'Liitetiedostot', 250, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'tuote', '1', '', 'Tuotteet', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'tuote!!!VIRANOMAISTUOTE!!!true&laji=V', '1', '', 'Viranomaistuotteet', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'tuotteen_alv', '1', '', 'Tuotteen ALV', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'tuotteen_avainsanat', '1', '', 'Tuotteen avainsanat', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito.php', 'tuotteen_toimittajat', '1', '', 'Tuotteen toimittajat', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Tuotehallinta', 'yllapito_tuotekuvat.php', '', '1', '', 'Tuotekuvien ylläpito', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'muokkaatilaus.php', 'TYOMAARAYS', '1', '', 'Työmääräykset', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'muokkaatilaus.php', 'TYOMAARAYSSUPER', '1', '', 'Muokkaa työmääräystä', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tilauskasittely/tilaus_myynti.php', 'TYOMAARAYS', '1', '', 'Uusi Työmääräys', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tilauskasittely/tulostakopio.php', 'TYOMAARAYS', '1', '', 'Työmääräyskopio', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tuote.php', '', '1', '', 'Tuotekysely', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tyomaarays/asennuskalenteri.php', '', '1', '', 'Asennuskalenteri', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tyomaarays/etsi.php', '', '1', '', 'Etsi työmääräys', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tyomaarays/maaraaikaishuollot.php', '', '1', '', 'Määräaikaishuollot', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Työmääräys', 'tyomaarays/tyojono.php', '', '1', '', 'Työjono', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'muokkaatilaus.php', 'VALMISTUS', '1', '', 'Valmistukset', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'muokkaatilaus.php', 'VALMISTUSSUPER', '1', '', 'Muokkaa valmistuksia', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/keraa.php', 'VALMISTUS', '1', '', 'Kerää valmistus', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/lahetteen_tulostusjono.php', 'VALMISTUS', '1', '', 'Tulosta valmistus', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/selaa_tilauksia.php', 'VALMISTUS', '1', '', 'Valmistusselaus', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/tilaus_myynti.php', 'VALMISTAASIAKKAALLE', '1', '', 'Valmista asiakkaalle', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/tilaus_myynti.php', 'VALMISTAVARASTOON', '1', '', 'Valmista varastoon', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/tulostakopio.php', 'VALMISTUS', '1', '', 'Valmistus kopio', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/valmista_tilaus.php', '', '1', '', 'Valmista tilaus', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/valmista_tilaus.php', 'KORJAA', '1', '', 'Korjaa valmistus', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/valmista_tilaus.php', 'TUOTE', '1', '', 'Valmista tuotteita', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/valmista_tilaus.php', 'TUTKAA', '1', '', 'Tutki valmistusta', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tilauskasittely/yhdista_valmistuksia.php', '', '1', '', 'Yhdistä valmistuksia', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'tuote.php', '', '1', '', 'Tuotekysely', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistus', 'valmistatuotteita.php', '', '1', '', 'Valmista tuotteita', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'monistalasku.php', '', '1', '', 'Monista lasku', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'muokkaatilaus.php', 'VALMISTUSMYYNTI', '1', '', 'Avoimet tilaukset', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'muokkaatilaus.php', 'VALMISTUSMYYNTISUPER', '1', '', 'Muokkaa tilausta', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'raportit/asiakkaantilaukset.php', 'VALMISTUSMYYNTI', '1', '', 'Asiakkaan tilaukset', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/jtselaus.php', '', '1', '', 'JT-selaus', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/keraa.php', 'VALMISTUSMYYNTI', '1', '', 'Kerää', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/lahetteen_tulostusjono.php', 'VALMISTUSMYYNTI', '1', '', 'Tulosta keräyslista', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tilauskanta.php', '', '1', '', 'Tilauskanta', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tilaus_myynti.php', 'PIKATILAUS', '1', '', 'Uusi Pikatilaus', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tilaus_myynti.php', 'RIVISYOTTO', '1', '', 'Uusi Tilaus', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tilaus_myynti.php', 'VALMISTAASIAKKAALLE', '1', '', 'Valmista asiakkaalle', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tilaus_myynti.php', 'VALMISTAVARASTOON', '1', '', 'Valmista varastoon', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tulostakopio.php', 'LAHETE', '1', '', 'Lähete kopio', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tulostakopio.php', 'LASKU', '1', '', 'Lasku kopio', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tulostakopio.php', 'VALMISTUS', '1', '', 'Valmistus kopio', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/valmista_tilaus.php', '', '1', '', 'Valmista tilaus', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/valmista_tilaus.php', 'KORJAA', '1', '', 'Korjaa valmistus', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/valmista_tilaus.php', 'TUOTE', '1', '', 'Valmista tuotteita', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/valmista_tilaus.php', 'TUTKAA', '1', '', 'Tutki valmistusta', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tilauskasittely/yhdista_valmistuksia.php', '', '1', '', 'Yhdistä valmistuksia', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Valmistusmyynti', 'tuote.php', '', '1', '', 'Tuotekysely', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'inventoi.php', '', '1', '', 'Inventointi', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'inventointi_listat.php', '', '1', '', 'Inventointilistat', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'muuvarastopaikka.php', '', '1', '', 'Varastopaikkojen muutos', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'pakkaamojen_selaus.php', '', '1', '', 'Pakkaamojen selaus', 300, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'rahtikirja-kopio.php', '', '1', '', 'Rahtikirjakopio', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'rahtikirja-tulostus.php', '', '1', '', 'Tulosta rahtikirjat', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'rahtikirja.php', 'lisaa', '1', '', 'Rahtikirjan syöttö', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'rahtikirja.php', 'muokkaa', '1', '', 'Muuta rahtikirjatietoja', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'rahtikirja_custom.php', '', '1', '', 'Tyhjä rahtikirja', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'raportit/inventointipoikkeamat.php', 'SUPER', '1', '', 'Inventointien korjaus', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'raportit/sarjanumerovssaldo.php', '', '1', '', 'Erät vs Saldot', 290, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'sarjanumeron_varmuutos.php', '', '1', '', 'Sarjanumeron arvomuutos', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/keraa.php', '', '1', '', 'Kerää', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/korjaa_kerays.php', '', '1', '', 'Korjaa keräys', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/lahetteen_tulostusjono.php', '', '1', '', 'Tulosta keräyslista', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/sarjanumeroseuranta.php', '', '1', '', 'Sarjanumeroseuranta', 250, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/toimita.php', '', '1', '', 'Toimita', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/tulostakopio.php', 'KERAYSLISTA', '1', '', 'Keräyslistakopio', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/tulostakopio.php', 'LAHETE', '1', '', 'Lähetekopio', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/tulostakopio.php', 'OSOITELAPPU', '1', '', 'Osoitelappukopio', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/tulostakopio.php', 'TILAUSTUOTETARRA', '1', '', 'Tilaustuotetarra kopio', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/tuote_selaus_haku.php', '', '1', '', 'Hae ja selaa', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', '', '1', '', 'Toimita/Laskuta', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tulosta_hyllytarrat.php', '', '1', '', 'Tulosta hyllytarrat', 280, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tulosta_keraysaineistotarrat.php', '', '1', '', 'Tulosta keräysaineistotarrat', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tulosta_tuotetarrat.php', '', '1', '', 'Tulosta tuotetarrat', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tulosta_tuotetarrat.php', 'YKS', '1', '', 'Tulosta tuotetarrat', 260, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tuote.php', '', '1', '', 'Tuotekysely', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'tuvar.php', '', '1', '', 'Tuotekysely (Varasto)', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'varastopaikkojen_siivous.php', '', '1', '', 'Varastopaikkojen siivous', 270, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'yllapito.php', 'etaisyydet', '1', '', 'Varastojen etäisyydet', 290, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varasto', 'yllapito.php', 'pakkaus', '1', '', 'Pakkaustiedot', 295, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/epakuranttiehdotus.php', '', '1', '', 'Epäkurantti-ehdotukset', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/inventointipoikkeamat.php', '', '1', '', 'Inventointi-poikkeamat', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/inventointiraportti.php', '', '1', '', 'Inventointiseuranta', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/keratytrivit.php', '', '1', '', 'Kerätyt rivit', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/laadunvalvonta.php', '', '1', '', 'Laadunvalvonta', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/loppuneet.php', '', '1', '', 'Loppuneet tuotteet', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/puutteet.php', '', '1', '', 'Puutelistaus', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/ressutuotteet.php', '', '1', '', 'Varastotilanne oletuspaikoilla', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/sarjanumerovssaldo.php', '', '1', '', 'Sarja vs saldo', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/toimitustapaseuranta.php', '', '1', '', 'Toimitustapaseuranta', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/toppivarastopaikat.php', '', '1', '', 'Paikkojen keräyskerrat', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/tuotepaikkalistaus.php', '', '1', '', 'Tuotepaikkalistaus', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/vaarasaldo.php', '', '1', '', 'Väärät saldot', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/varastonarvo-super.php', '', '1', '', 'Varastonarvo tuote', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/varastonarvo-tutki.php', '', '1', '', 'Tutki varastonarvoa', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/varastonarvo.php', '', '1', '', 'Varastonarvo', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastoraportit', 'raportit/varastotilasto.php', '', '1', '', 'Varastotilasto', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'kopioi_halytysrajoja.php', '', '1', '', 'Kopioi hälytysrajoja', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'muokkaatilaus.php', 'SIIRTOLISTA', '1', '', 'Siirtolistat', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'muokkaatilaus.php', 'SIIRTOLISTASUPER', '1', '', 'Muokkaa siirtolistaa', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'muuvarastopaikka.php', '', '1', '', 'Varastopaikkojen muutos', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'rahtikirja-tulostus.php', '', '1', '', 'Tulosta rahtikirjat', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'rahtikirja.php', 'lisaa_siirto', '1', '', 'Rahtikirjan syöttö', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'rahtikirja.php', 'muokkaa_siirto', '1', '', 'Muuta rahtikirjatietoja', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'siirrasaldo.php', '', '1', '', 'Siirrä saldoja', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/generoi_siirtolista.php', '', '1', '', 'Generoi siirtolista häly', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/keraa.php', 'SIIRTOLISTA', '1', '', 'Kerää siirtolista', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/lahetteen_tulostusjono.php', 'SIIRTOLISTA', '1', '', 'Tulosta siirtolista', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/tilaus_myynti.php', 'SIIRTOLISTA', '1', '', 'Uusi siirtolista', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/tulostakopio.php', 'OSOITELAPPU', '1', '', 'Osoitelappu kopio', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/tulostakopio.php', 'SIIRTOLISTA', '1', '', 'Siirtolista kopio', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/tulostakopio.php', 'VASTAANOTETUT', '1', '', 'Vastaanotetut kopio', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tilauskasittely/vastaanota.php', '', '1', '', 'Kuittaa vastaanotetuksi', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'tuote.php', '', '1', '', 'Tuotekysely', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Varastosiirrot', 'varastojen_halytysrajat.php', '', '1', '', 'Varastojen hälytysrajat', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'dummy3.php', '', '1', '', 'Täydentävä ilmoitus', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'intrastat.php', '', '1', '', 'Intrastat', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'muokkaatilaus.php', 'super', '1', '', 'Muokkaa tilausta', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'myyntires/eikateinen.php', '', '1', '', 'Ei käteinen', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'myyntires/maksunsyotto.php', '', '1', '', 'Suorituksen käsinsyöttö', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'myyntires/myyntilaskut_asiakasraportti.php', '', '1', '', 'Asiakkaan maksuraportti', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'myyntires/suoritusselailu.php', '', '1', '', 'Suoritukset', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'rahtikirja.php', 'lisaa', '1', '', 'Rahtikirjan syöttö', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'rahtikirja.php', 'muokkaa', '1', '', 'Muuta rahtikirjatietoja', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'raportit.php', 'paakirja', '1', '', 'Pää- ja päiväkirja', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'raportit/asiakkaantilaukset.php', 'MYYNTI', '1', '', 'Asiakkaan tilaukset', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'raportit/kateismyynnit.php', '', '1', '', 'Käteismyynnit', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/kotitullauskirjanpito.php', '', '1', '', 'Kotitullauskirjanpito', 220, 30, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/muokkaa_vienti_lisatiedot.php', '', '1', '', 'Muuta lisatietoja', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/taric_test.php', '', '1', '', 'Taric test', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/taydentava_vientiilmo.php', '', '1', '', 'Täydentävä vienti-ilmoitus', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/toimita.php', '', '1', '', 'Toimita tilaus', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'LAHETE', '1', '', 'Lähete kopio', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'LASKU', '1', '', 'Lasku kopio', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'OSOITELAPPU', '1', '', 'Osoitelappu kopio', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'PAKKALISTA', '1', '', 'Tulosta pakkalista', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'PROFORMA', '1', '', 'Proformalasku kopio', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'SAD', '1', '', 'Sad kopio', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/tulostakopio.php', 'VIENTIERITTELY', '1', '', 'Vientierittely kopio', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', 'VIENTI', '1', '', 'Tulosta vientilasku', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/vientipaperit_palautettu.php', '', '1', '', 'Vientipaperit', 220, 20, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/vientitilauksen_lisatiedot.php', '', '1', '', 'Viennin lisätiedot', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Vienti', 'tilauskasittely/vientitilauksen_lisatiedot.php', 'MUOKKAA', '1', '', 'Muuta lisatietoja', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'virtuaalipankkiaineisto.php', 'Aineisto pankkiin', '', '1', '', '', 55, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'aloita_synkronointi.php', '', '1', '', 'Alkusynkronointi', 460, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'avaa_keikka.php', '', '1', '', 'Avaa keikka', 350, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'csstest.php', '', '1', '', 'CSS Test', 530, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'db-index.php', '', '1', '', 'Tietokanta indexit', 300, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'db.php', '', '1', '', 'Tietokannat', 290, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'dokumentinhallinta_yllapito.php', '', '1', '', 'DocHandler', 440, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'dumppaa_mysqlkuvaus.php', '', '1', '', 'Tietokantarakenne', 280, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'ftp_kuvat.php', '', '1', '', 'Kuvat verkkokauppaan', 490, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'ftp_tuote_tiedot.php', '', '1', '', 'Tiedostot verkkokauppaan', 500, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'iltasiivo.php', '', '1', '', 'Iltasiivo', 450, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'jalkikorjaasarjamyynnit.php', '', '1', '', 'Laitemyynnin jälkilaskenta', 360, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'jalkikorjaavalmistukset.php', '', '1', '', 'Valmistusten jälkilaskenta', 370, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'korjaa_avoimia_myyntilaskuja.php', '', '1', '', 'Korjaa myyresko', 590, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'korjaa_kaatunut_vientilask.php', '', '1', '', 'Korjaa kaatunut vientilasku', 800, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'muokkaatilaus.php', 'LASKUTUSKIELTO', '1', '', 'Pyäytetyt tilaukset', 280, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'mysqlaliasyllapito.php', '', '1', '', 'Mysqlaliasylläpito', 480, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'nordeafactoring.php', '', '1', '', 'Nordea-factoring', 190, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'nordeafactoring.php', 'OKO', '1', '', 'OKO-factoring', 200, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'nouda_siirtoluettelo.php', '', '1', '', 'Tallennetut siirtoluettelot', 230, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'nouda_verkkolaskut_levylle.php', '', '1', '', 'Nouda verkkolaskut', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'pankki/patutestaus.php', '', '1', '', 'Patutestaus', 520, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'perulaskutus.php', '', '1', '', 'Peru laskutus', 410, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'peru_valmistus.php', '', '1', '', 'Peru valmistus', 390, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'peru_varastoonvienti.php', '', '1', '', 'Peru varastoonvienti', 380, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'raportit/abc_asiakas_aputaulun_rakennus.php', '', '1', '', 'ABC-apu asiakas', 330, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'raportit/abc_tuote_aputaulun_rakennus.php', '', '1', '', 'ABC-apu tuote', 310, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'sampofactoring.php', '', '1', '', 'Sampo-factoring', 180, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'sanakirja.php', '', '1', '', 'Sanakirja', 250, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'sveafactoring.php', '', '1', '', 'SVEA-factoring', 220, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'sveafactoring.php', 'OKO', '1', '', 'SVEA-factoring', 56, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'synkronoi_mysqlaliakset.php', '', '1', '', 'Mysqlaliaksien synkronointi', 270, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'synkronoi_sanakirja.php', '', '1', '', 'Sanakirjan synkronointi', 260, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'teeytunnus.php', '', '1', '', 'Y-tunnusgeneraattori', 15, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'teeytunnus.php', 'yhtio', '1', '', 'Tee ytunnus', 5, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'testaakassaalvit.php', '', '1', '', 'Kassa-alv korjaus', 500, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tikon.php', '', '1', '', 'TIKON file', 520, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/korjaa_kehahin.php', '', '1', '', 'Korjaa kehahin', 502, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/seb_factoring.php', '', '1', '', 'SEB-factoring', 210, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/tulostasisaiset.php', '', '1', '', 'Tulosta Sisäiset', 170, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/uudelleenluo_laskuaineisto.php', '', '1', '', 'Luo laskutusaineisto', 430, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/vaihda_tila.php', '', '1', '', 'Vaihda tilauksen tila', 340, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', '', '1', '', 'Toimita ja Laskuta tilaus', 49, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/valitse_laskutettavat_tilaukset.php', 'VAINLASKUTA', '1', '', 'Laskuta tilaus', 290, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilauskasittely/verkkolasku.php', '', '1', '', 'Aja Laskut', 160, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'tilaus_siivo.php', '', '1', '', 'Tilaussiivous', 420, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'uudelleenlaheta-tilvah.php', '', '1', '', 'Tilvah uudelleen', 400, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'uusiyritys.php', '', '1', '', 'Luo uusi yritys', 510, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'verkkolaskuvirheet.php', '', '1', '', 'Virheelliset verkkolaskut', 240, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yhdistasarjanumerorivit.php', '', '1', '', 'Laitemyynnin yhdistys/korjaus', 470, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'abc_parametrit', '1', '', 'ABC parametrit', 320, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'avainsana', '1', '', 'Avainsanat', 30, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'factoring', '1', '', 'Factoring-sopimukset', 80, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'kassalipas', '1', '', 'Kassalippaat', 130, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'kirjoittimet', '1', '', 'Kirjoittimet', 110, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'korvaavat_kiellot', '1', '', 'Korvaavat kiellot', 100, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'maksuehto', '1', '', 'Maksuehdot', 150, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'pakkaamo', '1', '', 'Pakkaamot', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'pankkiyhteystiedot', '1', '', 'Pankkiyhteystiedot', 120, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'rahtimaksut', '1', '', 'Rahtimaksut', 140, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'rahtisopimukset', '1', '', 'Rahtisopimukset', 70, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'toimitustapa', '1', '', 'Toimitustavat', 90, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'varaston_tulostimet', '1', '', 'Varaston tulostusalueet', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'varastopaikat', '1', '', 'Varastopaikat', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'yhtio', '1', '', 'Yhtiön tiedot', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'yhtion_parametrit', '1', '', 'Yhtiön parametrit', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Ylläpito', 'yllapito.php', 'yhtion_toimipaikat', '1', '', 'Yhtiön toimipaikat', 15, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Yrityspeli', 'yrityspeli/automaattitilausraportti.php', '', '1', '', 'Automaattitilaukset', 60, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Yrityspeli', 'yrityspeli/laskutusraportti.php', '', '1', '', 'Laskutusraportti', 50, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Yrityspeli', 'yrityspeli/painoarvot.php', '', '1', '', 'Painoarvot', 10, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Yrityspeli', 'yrityspeli/sutinakerroin.php', '', '1', '', 'Kertoimet', 20, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Yrityspeli', 'yrityspeli/tarkistusraportti.php', '', '1', '', 'Tarkistusraportti', 40, 0, 'Admin profil', '$yhtio', '')
			, ('superuser', 'Yrityspeli', 'yrityspeli/yritysraportti.php', '', '1', '', 'Yritysraportti', 30, 0, 'Admin profil', '$yhtio', '');";

	$query = utf8_decode($query);
	$result = mysql_query($query) or pupe_error($query);

	$query = "UNLOCK TABLES";
	$result = mysql_query($query) or pupe_error($query);
?>